services:
  db:
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=liane
      - POSTGRES_PASSWORD=liane_dev
      - POSTGRES_DB=liane_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes: 
  postgres_data: